volumes:
  pg_demo:

services:
  ipa_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ipa_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ipa_db:5432/ipa_db"